import "../styles/globals.css";

const geistSans = ({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = ({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}){
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
